######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 10 19:58:09 2012
######################################################################

TEMPLATE = app
TARGET = calcGPA_v2.0
DEPENDPATH += .
INCLUDEPATH += .
ICON = calcICON.icns

# Input
HEADERS += calcGPA.h
SOURCES += calcGPA.cpp main.cpp
RESOURCES += calcGPAresources.qrc
