#############################################################################
# Makefile for building: calcGPA_v2.0.app/Contents/MacOS/calcGPA_v2.0
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Sep 29 23:05:55 2015
# Project:  calcGPA.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile calcGPA.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES) -std=c11
CXXFLAGS      = -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES) -std=c++11
INCPATH       = -I/usr/local/Cellar/qt/4.8.7/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/include -I. -I. -F/usr/local/Cellar/qt/4.8.7/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.7/lib -L/usr/local/Cellar/qt/4.8.7/lib -framework QtGui -L/usr/local/Cellar/qt/4.8.7/lib -F/usr/local/Cellar/qt/4.8.7/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = calcGPA.cpp \
		main.cpp moc_calcGPA.cpp \
		qrc_calcGPAresources.cpp
OBJECTS       = calcGPA.o \
		main.o \
		moc_calcGPA.o \
		qrc_calcGPAresources.o
DIST          = /usr/local/Cellar/qt/4.8.7/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/include_source_dir.prf \
		calcGPA.pro
QMAKE_TARGET  = calcGPA_v2.0
DESTDIR       = 
TARGET        = calcGPA_v2.0.app/Contents/MacOS/calcGPA_v2.0

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile calcGPA_v2.0.app/Contents/PkgInfo calcGPA_v2.0.app/Contents/Resources/empty.lproj calcGPA_v2.0.app/Contents/Info.plist calcGPA_v2.0.app/Contents/Resources/calcICON.icns $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) calcGPA_v2.0.app/Contents/MacOS/ || $(MKDIR) calcGPA_v2.0.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: calcGPA.pro  /usr/local/Cellar/qt/4.8.7/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.7/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile calcGPA.pro
/usr/local/Cellar/qt/4.8.7/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile calcGPA.pro

calcGPA_v2.0.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) calcGPA_v2.0.app/Contents || $(MKDIR) calcGPA_v2.0.app/Contents 
	@$(DEL_FILE) calcGPA_v2.0.app/Contents/PkgInfo
	@echo "APPL????" >calcGPA_v2.0.app/Contents/PkgInfo
calcGPA_v2.0.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) calcGPA_v2.0.app/Contents/Resources || $(MKDIR) calcGPA_v2.0.app/Contents/Resources 
	@touch calcGPA_v2.0.app/Contents/Resources/empty.lproj
	
calcGPA_v2.0.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) calcGPA_v2.0.app/Contents || $(MKDIR) calcGPA_v2.0.app/Contents 
	@$(DEL_FILE) calcGPA_v2.0.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,calcICON.icns,g" -e "s,@EXECUTABLE@,calcGPA_v2.0,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.7/mkspecs/unsupported/macx-clang-libc++/Info.plist.app >calcGPA_v2.0.app/Contents/Info.plist
calcGPA_v2.0.app/Contents/Resources/calcICON.icns: calcICON.icns
	@$(CHK_DIR_EXISTS) calcGPA_v2.0.app/Contents/Resources/ || $(MKDIR) calcGPA_v2.0.app/Contents/Resources/ 
	@$(DEL_FILE) calcGPA_v2.0.app/Contents/Resources/calcICON.icns
	@$(COPY_FILE) calcICON.icns calcGPA_v2.0.app/Contents/Resources/calcICON.icns
dist: 
	@$(CHK_DIR_EXISTS) .tmp/calcGPA_v2.01.0.0 || $(MKDIR) .tmp/calcGPA_v2.01.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/calcGPA_v2.01.0.0/ && $(COPY_FILE) --parents calcGPA.h .tmp/calcGPA_v2.01.0.0/ && $(COPY_FILE) --parents calcGPAresources.qrc .tmp/calcGPA_v2.01.0.0/ && $(COPY_FILE) --parents calcGPA.cpp main.cpp .tmp/calcGPA_v2.01.0.0/ && (cd `dirname .tmp/calcGPA_v2.01.0.0` && $(TAR) calcGPA_v2.01.0.0.tar calcGPA_v2.01.0.0 && $(COMPRESS) calcGPA_v2.01.0.0.tar) && $(MOVE) `dirname .tmp/calcGPA_v2.01.0.0`/calcGPA_v2.01.0.0.tar.gz . && $(DEL_FILE) -r .tmp/calcGPA_v2.01.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r calcGPA_v2.0.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_calcGPA.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_calcGPA.cpp
moc_calcGPA.cpp: calcGPA.h
	/usr/local/Cellar/qt/4.8.7/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ calcGPA.h -o moc_calcGPA.cpp

compiler_rcc_make_all: qrc_calcGPAresources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_calcGPAresources.cpp
qrc_calcGPAresources.cpp: calcGPAresources.qrc \
		Copyright.txt \
		icon.png
	/usr/local/Cellar/qt/4.8.7/bin/rcc -name calcGPAresources calcGPAresources.qrc -o qrc_calcGPAresources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

calcGPA.o: calcGPA.cpp calcGPA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calcGPA.o calcGPA.cpp

main.o: main.cpp calcGPA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_calcGPA.o: moc_calcGPA.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calcGPA.o moc_calcGPA.cpp

qrc_calcGPAresources.o: qrc_calcGPAresources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_calcGPAresources.o qrc_calcGPAresources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

